# Use a basic Python image
FROM python:3.10-slim


# Create a working directory
WORKDIR /app

# Install dependencies


# Install the dependencies from requirements.txt
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy your application files into a container
COPY . .

#
EXPOSE 8501

# Add a health check
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

# Specify a command to run Streamlit
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]